#!/usr/bin/env python3

import argparse
import subprocess
import re
from colorama import Fore, Style


VFLAGS = ["--leak-check=full", "--track-origins=yes", "--show-reachable=yes"]

def clean_output(output):
    verbose = r'==\d{1,5}=='
    return re.sub(verbose,'',output)


def color_output(output):
    error_sumary = re.compile(r'ERROR SUMMARY:.*')
    output = error_sumary.sub(lambda x: Fore.RED + x.group() + Style.RESET_ALL, output)
    
    file_and_line = re.compile(r'\(.*.c:\d{1,5}\)')
    output = file_and_line.sub(lambda x: Fore.GREEN + x.group() + Style.RESET_ALL, output)
    return output


def call_valgrind(exec, flags=VFLAGS):
    valgrind = subprocess.Popen(["valgrind", *flags, exec],
                                stdin=subprocess.DEVNULL, 
                                stdout=subprocess.PIPE, 
                                stderr=subprocess.STDOUT)
    out, _ = valgrind.communicate()
    return out.decode("utf-8")

def valgreen():
    parser = argparse.ArgumentParser()
    parser.add_argument('exec', help='Executable file passed to Valgrind', type=str)
    args = parser.parse_args()
    output = call_valgrind(args.exec)
    cleaned_output = clean_output(output)
    colored_output = color_output(cleaned_output)
    print(colored_output)


if __name__ == "__main__":
    valgreen()